<h1>Import the libraries</h1>

In [6]:
import pandas as pd
from sklearn.impute import KNNImputer

<h1>Read the csv file</h1>

In [7]:
df = pd.read_csv('data/data_dog.csv')
df.head()

,size_dog,eye_circularity,skull_circularity,ear_size,eyes_distance,ear_form,hair_tone,nose_elongatedness,weight_dog,muzzle_form,skin_tone_main,skin_pattern_complexity,body_length,tail_length,hair_curlness,hair_length,leg_front_number,leg_back_number,breuni_class
0,95,48.0,83.0,178.0,72.0,10,162.0,42.0,20.0,159,176.0,379.0,184.0,70.0,6.0,16.0,187.0,197,fashion_lifestyle_elite
1,91,41.0,84.0,141.0,57.0,9,149.0,45.0,19.0,143,170.0,330.0,158.0,72.0,9.0,14.0,189.0,199,fashion_lifestyle_elite
2,104,50.0,106.0,209.0,66.0,10,207.0,32.0,23.0,158,223.0,635.0,220.0,73.0,14.0,9.0,188.0,196,main_stream
3,93,41.0,82.0,159.0,63.0,9,144.0,46.0,19.0,143,160.0,309.0,127.0,63.0,6.0,10.0,199.0,207,fashion_lifestyle_elite
4,85,44.0,70.0,205.0,103.0,52,149.0,45.0,19.0,144,241.0,325.0,188.0,127.0,9.0,11.0,180.0,183,trendy

<h1>Missing Values</h1>

In [8]:
df.isna().sum()

size_dog                   0
eye_circularity            5
skull_circularity          4
ear_size                   6
eyes_distance              2
ear_form                   0
hair_tone                  1
nose_elongatedness         1
weight_dog                 3
muzzle_form                0
skin_tone_main             3
skin_pattern_complexity    2
body_length                2
tail_length                4
hair_curlness              6
hair_length                1
leg_front_number           1
leg_back_number            0
breuni_class               0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   size_dog                 846 non-null    int64
 1   eye_circularity          841 non-null    float64
 2   skull_circularity        842 non-null    float64
 3   ear_size                 840 non-null    float64
 4   eyes_distance            844 non-null    float64
 5   ear_form                 846 non-null    int64
 6   hair_tone                845 non-null    float64
 7   nose_elongatedness       845 non-null    float64
 8   weight_dog               843 non-null    float64
 9   muzzle_form              846 non-null    int64
 10  skin_tone_main           843 non-null    float64
 11  skin_pattern_complexity  844 non-null    float64
 12  body_length              844 non-null    float64
 13  tail_length              842 non-null    float64
 14  hair_curlness            840 non-null    float64
 15  hair_length              845 non-null    float64
 16  leg_front_number         845 non-null    float64
 17  leg_back_number          846 non-null    int64
 18  breuni_class             846 non-null    object
dtypes: float64(14), int64(4), object(1)
memory usage: 125.7+ KB

In [10]:
len(df[df.isna().any(axis=1)])

33

<h1>Deleting missing values?</h1>
rows with missing vallues = 33/846 = 3.9%

In [11]:
dogStr_df = df[['breuni_class']]
dogStr_df.head()

              breuni_class
0  fashion_lifestyle_elite
1  fashion_lifestyle_elite
2              main_stream
3  fashion_lifestyle_elite
4                   trendy

In [12]:
dogNoStr_df = df.drop(columns='breuni_class')

<h1>Fill values with Neughbors</h1>

In [13]:
knnimp = KNNImputer()
dogNoString_imp = pd.DataFrame(knnimp.fit_transform(dogNoStr_df),columns= dogNoStr_df.columns)

In [14]:
dogNoString_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   size_dog                 846 non-null    float64
 1   eye_circularity          846 non-null    float64
 2   skull_circularity        846 non-null    float64
 3   ear_size                 846 non-null    float64
 4   eyes_distance            846 non-null    float64
 5   ear_form                 846 non-null    float64
 6   hair_tone                846 non-null    float64
 7   nose_elongatedness       846 non-null    float64
 8   weight_dog               846 non-null    float64
 9   muzzle_form              846 non-null    float64
 10  skin_tone_main           846 non-null    float64
 11  skin_pattern_complexity  846 non-null    float64
 12  body_length              846 non-null    float64
 13  tail_length              846 non-null    float64
 14  hair_curlness            846 non-null    float64
 15  hair_length              846 non-null    float64
 16  leg_front_number         846 non-null    float64
 17  leg_back_number          846 non-null    float64
dtypes: float64(18)
memory usage: 119.1 KB

In [15]:
filledDog_df=dogNoString_imp.join(dogStr_df)
filledDog_df.head()

,size_dog,eye_circularity,skull_circularity,ear_size,eyes_distance,ear_form,hair_tone,nose_elongatedness,weight_dog,muzzle_form,skin_tone_main,skin_pattern_complexity,body_length,tail_length,hair_curlness,hair_length,leg_front_number,leg_back_number,breuni_class
0,95.0,48.0,83.0,178.0,72.0,10.0,162.0,42.0,20.0,159.0,176.0,379.0,184.0,70.0,6.0,16.0,187.0,197.0,fashion_lifestyle_elite
1,91.0,41.0,84.0,141.0,57.0,9.0,149.0,45.0,19.0,143.0,170.0,330.0,158.0,72.0,9.0,14.0,189.0,199.0,fashion_lifestyle_elite
2,104.0,50.0,106.0,209.0,66.0,10.0,207.0,32.0,23.0,158.0,223.0,635.0,220.0,73.0,14.0,9.0,188.0,196.0,main_stream
3,93.0,41.0,82.0,159.0,63.0,9.0,144.0,46.0,19.0,143.0,160.0,309.0,127.0,63.0,6.0,10.0,199.0,207.0,fashion_lifestyle_elite
4,85.0,44.0,70.0,205.0,103.0,52.0,149.0,45.0,19.0,144.0,241.0,325.0,188.0,127.0,9.0,11.0,180.0,183.0,trendy

<h1>Export finished Dog Dataset</h1>

In [16]:
filledDog_df.to_csv('data/test_and_training_data/v1_data_dog_normal.csv', index=False)